# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/moorer/projects/rya_c/rya

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/moorer/projects/rya_c/rya

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/moorer/projects/rya_c/rya/CMakeFiles /Users/moorer/projects/rya_c/rya/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/moorer/projects/rya_c/rya/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rya

# Build rule for target.
rya: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rya
.PHONY : rya

# fast build rule for target.
rya/fast:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/build
.PHONY : rya/fast

src/rya.o: src/rya.c.o

.PHONY : src/rya.o

# target to build an object file
src/rya.c.o:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya.c.o
.PHONY : src/rya.c.o

src/rya.i: src/rya.c.i

.PHONY : src/rya.i

# target to preprocess a source file
src/rya.c.i:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya.c.i
.PHONY : src/rya.c.i

src/rya.s: src/rya.c.s

.PHONY : src/rya.s

# target to generate assembly for a file
src/rya.c.s:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya.c.s
.PHONY : src/rya.c.s

src/rya_file.o: src/rya_file.c.o

.PHONY : src/rya_file.o

# target to build an object file
src/rya_file.c.o:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya_file.c.o
.PHONY : src/rya_file.c.o

src/rya_file.i: src/rya_file.c.i

.PHONY : src/rya_file.i

# target to preprocess a source file
src/rya_file.c.i:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya_file.c.i
.PHONY : src/rya_file.c.i

src/rya_file.s: src/rya_file.c.s

.PHONY : src/rya_file.s

# target to generate assembly for a file
src/rya_file.c.s:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya_file.c.s
.PHONY : src/rya_file.c.s

src/rya_format.o: src/rya_format.c.o

.PHONY : src/rya_format.o

# target to build an object file
src/rya_format.c.o:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya_format.c.o
.PHONY : src/rya_format.c.o

src/rya_format.i: src/rya_format.c.i

.PHONY : src/rya_format.i

# target to preprocess a source file
src/rya_format.c.i:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya_format.c.i
.PHONY : src/rya_format.c.i

src/rya_format.s: src/rya_format.c.s

.PHONY : src/rya_format.s

# target to generate assembly for a file
src/rya_format.c.s:
	$(MAKE) -f CMakeFiles/rya.dir/build.make CMakeFiles/rya.dir/src/rya_format.c.s
.PHONY : src/rya_format.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rya"
	@echo "... src/rya.o"
	@echo "... src/rya.i"
	@echo "... src/rya.s"
	@echo "... src/rya_file.o"
	@echo "... src/rya_file.i"
	@echo "... src/rya_file.s"
	@echo "... src/rya_format.o"
	@echo "... src/rya_format.i"
	@echo "... src/rya_format.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

